import type { Article, Citation } from '../types';
import type { ArticleSource } from '../utils/articleMetrics';
import { extractCitationsFromText } from '../utils/citationUtils';
import { CitationList } from './CitationList';
import { ArticleContent } from './ArticleContent';
import { Database, Sparkles, FileText, Zap } from 'lucide-react';

interface ArticleViewProps {
  article: Article;
  source?: ArticleSource | null;
  onCitationClick?: (citation: Citation) => void;
}

const sourceConfig: Record<ArticleSource, { label: string; icon: any; color: string; description: string }> = {
  cache: {
    label: 'Cached',
    icon: Zap,
    color: 'text-green-400 bg-green-900/20',
    description: 'Loaded from cache (instant)',
  },
  grokipedia_url: {
    label: 'Grokipedia',
    icon: Database,
    color: 'text-blue-400 bg-blue-900/20',
    description: 'Fetched from Grokipedia URL',
  },
  grokipedia_topic: {
    label: 'Grokipedia',
    icon: Database,
    color: 'text-blue-400 bg-blue-900/20',
    description: 'Found on Grokipedia by topic',
  },
  grok_api: {
    label: 'AI Generated',
    icon: Sparkles,
    color: 'text-purple-400 bg-purple-900/20',
    description: 'Generated by Grok AI',
  },
  fallback: {
    label: 'Fallback',
    icon: FileText,
    color: 'text-yellow-400 bg-yellow-900/20',
    description: 'Using fallback content',
  },
};

export function ArticleView({ article, source, onCitationClick }: ArticleViewProps) {
  // Extract citations from content if not already extracted
  const citations = article.citations.length > 0 
    ? article.citations 
    : extractCitationsFromText(article.content);

  const sourceInfo = source ? sourceConfig[source] : null;
  const SourceIcon = sourceInfo?.icon;

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 fade-in">
      <article className="bg-[#1a1a1a] rounded-lg border border-[#2a2a2a] p-8 hover-lift hover:border-[#3a3a3a]">
        <h1 className="text-4xl font-bold text-[#e5e5e5] mb-4 tracking-tight">{article.title}</h1>
        
        <div className="flex items-center gap-3 text-sm text-[#888] mb-6 pb-6 border-b border-[#2a2a2a]">
          <span>Last updated: {new Date(article.updatedAt).toLocaleDateString()}</span>
          <span className="text-[#444]">•</span>
          <span className="flex items-center gap-1">
            <span>{citations.length}</span>
            <span>citation{citations.length !== 1 ? 's' : ''}</span>
          </span>
          {sourceInfo && SourceIcon && (
            <>
              <span className="text-[#444]">•</span>
              <div className={`flex items-center gap-1.5 px-2 py-1 rounded ${sourceInfo.color}`} title={sourceInfo.description}>
                <SourceIcon className="w-3.5 h-3.5" />
                <span className="text-xs font-medium">{sourceInfo.label}</span>
              </div>
            </>
          )}
        </div>

        <ArticleContent content={article.content} citations={citations} />
        
        <div className="mt-8 pt-8 border-t border-[#2a2a2a]">
          <h2 className="text-2xl font-semibold mb-6 text-[#e5e5e5] tracking-tight">Citations</h2>
          <CitationList citations={citations} onCitationClick={onCitationClick} />
        </div>
      </article>
    </div>
  );
}

